FROM node:13.12.0-alpine
WORKDIR /Norton
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json ./
COPY package-lock.json ./
RUN yarn
RUN npm install react-scripts@3.4.1
COPY . ./
CMD ["yarn", "start"]