version: '3.7'
services:
    frontend:
        stdin_open: true
        build:
            dockerfile: Dockerfile.dev
            context: ./norton
        volumes:
            - ./norton/node_modules
            - ./client/app
            

